server:
  port: 8095
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        cache.use_second_level_cache: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        cache.queries: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-profiles?ssl=false
    username: user
    password: password
springdoc.api-docs.path: /api/v1/petprofiles/api-doc
logging:
  level:
    com.agenatech: DEBUG
