server:
  port: 8081
security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /profiles
    - /profiles/**
    - /pets/**
    - /pets
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: userProfilesPrincipalGetPatchDelete
          uri: http://localhost:8095
          predicates:
            - Path=/profiles/me
            - Method=GET,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: userProfilesPut
          uri: http://localhost:8095
          predicates:
            - Path=/profiles/**
            - Method=PUT
        - id: serviceFunctions
          uri: http://localhost:8095
          predicates:
            - Path=/service/**
#        - id: userProfilesPrincipal
#          uri: http://localhost:8095
#          predicates:
#            - Path=/profiles**
#            - Method=GET,POST
#          filters:
#            - AddPrincipalToPathFilter
#        - id: userProfilesPlain
#          uri: http://localhost:8095
#          predicates:
#            - Path=/profiles**
#            - Method=PUT,POST
        - id: petprofiles
          uri: http://localhost:8095
          predicates:
            - Path=/pets, /pets/**
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: test-gateway
            client-secret: '{cipher}411946586be6b69f2ad96a02710e50a50d2e76a21c0bc9a78d392451e9e0fc1c61d95b885a97ff9b131877ff5efb293182790c5a25b86b6ce1f750614754f1fb'
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
keycloak-client:
  server-url: http://localhost:8085/auth
  realm: spring-micro-main
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
springdoc:
  packagesToScan: com.agenatech