spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: profiles
#          todo change
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/**
        - id: auth-client
          #          todo change
          uri: http://auth-client
          predicates:
            - Path=/api/v1/auth/**, /api/v1/auth-client/**
keycloak-client:
  #          todo change
  server-url: http://keycloak/auth
