server:
  port: 9132
service:
  json-url: /v2/api-docs
  version: 2.0
  ignored-services:
    - consul
    - config-server
    - swagger-server
    - api-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.agenatech: DEBUG