spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}ab5bc1b489e067a0810b45bb9f9f207d6f24e77c0805c5990dcf6b90dffbee7a'
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cloud:
    loadbalancer:
      instances:
        - name: auth-server
          servers: localhost:8080
#auth-server:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: localhost:8080


