spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}ab5bc1b489e067a0810b45bb9f9f207d6f24e77c0805c5990dcf6b90dffbee7a'
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
keycloak:
  auth-server-url: ${keycloak-client.server-url}/auth
  realm: ${keycloak-client.realm}
  credentials:
    secret: '{cipher}6c1ca654778f10321f096b20143493b40337ad90c5b0f991b658c918aecdcd9533dae74a7293a8ad7c1e60d5a8bbde8fc1ab72814c727fd13f6431748785b2bb'
  use-resource-role-mappings: true
  resource: test-gateway
  ssl-required: external
