spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}ab5bc1b489e067a0810b45bb9f9f207d6f24e77c0805c5990dcf6b90dffbee7a'
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
keycloak:
  auth-server-url: ${keycloak-client.server-url}/auth
  realm: ${keycloak-client.realm}
  credentials:
    secret: '{cipher}411946586be6b69f2ad96a02710e50a50d2e76a21c0bc9a78d392451e9e0fc1c61d95b885a97ff9b131877ff5efb293182790c5a25b86b6ce1f750614754f1fb'
  use-resource-role-mappings: true
  resource: test-gateway
  ssl-required: external
  securityConstraints[0].authRoles[0]: '*'
  securityConstraints[0].securityCollections[0].patterns[0]: '/*'
