server:
  forward-headers-strategy: framework
  port: 8989
spring:
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/profiles?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          queries: true
          ehcache:
            missing_cache_strategy: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  # Producer properties
  kafka:
    enabled: true
    bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: b-1.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.agenatech-dev.9cindp.c2.kafka.eu-north-1.amazonaws.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: profile:com.agenatech.solutions.profiles.model.UserProfile
    topic:
      name: test-topic-22
      replicas: 2
      partitions: 3

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc.api-docs.path: /api/v1/profiles/api-doc
logging:
  level:
    com.agenatech: DEBUG
health:
  config:
    enabled: false





