spring:
  cloud:
    consul:
      host: consul
      port: 8500
  datasource:
    url: jdbc:postgresql://profiles-db:5432/profiles?ssl=false
#    driverClassName: org.h2.Driver
    username: super-admin
    password: super-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
keycloak-client:
  server-url: http://keycloak:8080
keycloack:
  secret: '{cipher}126874a012205cf99c50561321079851dc09c33f0f63b4ccc314f6a864be26fc8a3f2e913d0c31f79e9f0e0acad5731711125ea304618c32d87842238c76fd0a'