server:
  port: 8989
feign.client.config.default.loggerLevel: full
logging:
  level:
    com.agenatech: DEBUG
keycloack:
  url: ${keycloak-client.server-url}
  admin-secret: '{cipher}6090ac930c0b2cefbaec1808ceef22ebcf8aac1e76269ae94ac49f42c608a858539feb13ffd4138a46cea4a6dfd3deeb196196b3cb7561749d0fc169af2d13cd'
  cli-token-uri: auth/realms/master/protocol/openid-connect/token
  users-uri: auth/admin/realms/${keycloak-client.realm}/users
  email-actions-uri: auth/admin/realms/${keycloak-client.realm}/users/{id}/execute-actions-email
keycloak-client:
  server-url: http://localhost:8085
  realm: spring-micro-main
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        cache.use_second_level_cache: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        cache.queries: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

