spring:
  cloud:
    consul:
      host: consul
      port: 8500
  datasource:
    url: jdbc:postgresql://profiles-db:5432/profiles?ssl=false
    username: super-admin
    password: super-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
keycloak-client:
  server-url: http://keycloak:8080
keycloack:
  secret: '{cipher}6fce16c4ffc2f64ae78db86916b757f3d371a1e933c10d79c2582937c1c1aee559126a019cbf40f8e8187d6e34d832e6df43a84ae7cf4a9777e7625de6e860cb'
auth-server:
  admin-secret: '{cipher}4f5891ada63f4e8035b6dea8b17f43ef137fcfe18be4a4c82cb74499bd5b28b71b139cedf075641dbb953b9c3444e5c75e046f002773b2cde899cdc66caf2e6b'